name: Quantum Swarm Heating Add-on
version: "1.0.9"
slug: quantum_swarm_heating
description: Adaptive RL heating control with PyTorch in HA
arch:
  - amd64
startup: application
boot: auto
hassio_api: true
homeassistant_api: true
apparmor: false
options:
  tado_rooms: "[]"
  independent_sensors: "[]"
  battery_entities: "{}"
  global_entities: "{}"
schema:
  tado_rooms: str?
  independent_sensors: str?
  battery_entities: str?
  global_entities: str?

